version: 2
seeds:
  - name: produktkategorie_20250103
    config:
      column_types:
        KatID: varchar(2000000)
        Rabatt: decimal(18,2)
        Von: varchar(2000000)
        Bis: varchar(2000000)
        Festlegung: varchar(2000000)
        Stand: varchar(2000000)
